### ISSUE TITLE
Model Not Displaying in Cesium After Compressing

### ISSUE THREAD

**Issue by pedro-mar** [Geodan/compressor5000#5]
I encountered an issue when trying to run the Docker command:

```
$ docker run -v $(pwd):/tiles -it compressor5000
```
I initially faced errors due to Windows-style line endings (\r\n) in the compress.sh script. I resolved this by converting the line endings to Unix-style using the dos2unix tool while working in WSL.

After successfully running the script, the compressed model was generated without any errors. However, when trying to display the compressed model in Cesium, it did not appear. The model loads without throwing any errors, but remains invisible. In contrast, the original uncompressed model displays correctly.

Any suggestions for resolving this or understanding why the compressed model is not rendering would be greatly appreciated.

**Comment by bertt** [comment]
Hi,

Can you try using the existing image?

```
docker pull geodan/compressor5000
docker run geodan/compressor5000
```

shall take a look at the line endings

**Comment by bertt** [comment]
Fix line endings (when cloning on windows) globally: do 

```
git config --global core.autocrlf false
```

Or per git clone:

```
git clone -c core.autocrlf false
```

**Comment by pedro-mar** [comment]
Hi,

Thank you for your prompt response!

I ran the commands as you suggested.

This resolved the Windows line ending issue, and the compressed B3DM models were generated successfully. However, when I attempted to visualize the compressed models in Cesium, they remain invisible. The uncompressed model displays correctly, but the compressed version does not show up at all.

**Comment by bertt** [comment]
ok, can you attach one of the input b3dm's?

**Comment by pedro-mar** [comment]
Since the dataset is large, I’m sharing a subset for reference. Here are the links:

- [Estrela_recorte.zip](https://github.com/user-attachments/files/17558801/Estrela_recorte.zip): the uncompressed version

- [Estrela_recorte_compressed.zip](https://github.com/user-attachments/files/17558807/Estrela_recorte_compressed.zip): the compressed version

Please let me know if any other details are needed.

Thank you!

**Comment by bertt** [comment]
took a look at a.b3dm in Estrela_recorte.zip\Estrela_recorte\Data - the glb file in the b3dm is already Draco compressed by 'Agisoft Metashape' (I've used https://github.com/bertt/b3dm.tooling to get from b3dm to glb).

**Comment by pedro-mar** [comment]
Thank you for taking the time to investigate and for your support. I looked into it further, and you're right, Agisoft Metashape does indeed apply Draco compression by default. Thanks for clarifying that!

**Comment by bertt** [comment]
Btw there is an old issue about this https://github.com/Geodan/compressor5000/issues/2 to improve the error handling when there is already Draco compression.
